<?php
return[
    'permission' => [
         'userIndex'=>[
         		'name'=>'user_index'
         ],
         'userCreate'=>[
         		'name'=>'user_create'
         ],
         'userView'=>[
         		'name'=>'user_view'
         ],
         'userEdit'=>[
         		'name'=>'user_edit'
         ],
         'userDeleted'=>[
         		'name'=>'user_delete'
         ],
         'roleIndex'=>[
         		'name'=>'role_index'
         ],
         'roleCreate'=>[
         		'name'=>'role_create'
         ],
         'roleView'=>[
         		'name'=>'role_view'
         ],
         'roleEdit'=>[
         		'name'=>'role_edit'
         ],
         'roleDeleted'=>[
         		'name'=>'role_delete'
         ],
         'permissionIndex'=>[
         		'name'=>'permission_index'
         ],
         'permissionCreate'=>[
         		'name'=>'permission_create'
         ],
         'permissionView'=>[
         		'name'=>'permission_view'
         ],
         'permissionEdit'=>[
         		'name'=>'permission_edit'
         ],
         'permissionDeleted'=>[
         		'name'=>'permission_delete'
         ],
         'bannerIndex'=>[
         		'name'=>'banner_index'
         ],
         'bannerCreate'=>[
         		'name'=>'banner_create'
         ],
         'bannerView'=>[
         		'name'=>'banner_view'
         ],
         'bannerEdit'=>[
         		'name'=>'banner_edit'
         ],
         'bannerDeleted'=>[
         		'name'=>'banner_delete'
         ],
         'productIndex'=>[
         		'name'=>'product_index'
         ],
         'productCreate'=>[
         		'name'=>'product_create'
         ],
         'productView'=>[
         		'name'=>'product_view'
         ],
         'productEdit'=>[
         		'name'=>'product_edit'
         ],
         'productDeleted'=>[
         		'name'=>'product_delete'
         ],
         'categoryIndex'=>[
         		'name'=>'category_index'
         ],
         'categoryCreate'=>[
         		'name'=>'category_create'
         ],
         'categoryView'=>[
         		'name'=>'category_view'
         ],
         'categoryEdit'=>[
         		'name'=>'category_edit'
         ],
         'categoryDeleted'=>[
         		'name'=>'category_delete'
         ],
          'productIndex'=>[
         		'name'=>'product_index'
         ],
         'productCreate'=>[
         		'name'=>'product_create'
         ],
         'productView'=>[
         		'name'=>'product_view'
         ],
         'productEdit'=>[
         		'name'=>'product_edit'
         ],
         'productDeleted'=>[
         		'name'=>'product_delete'
         ],
         'couponIndex'=>[
         		'name'=>'coupon_index'
         ],
         'couponCreate'=>[
         		'name'=>'coupon_create'
         ],
         'couponView'=>[
         		'name'=>'coupon_view'
         ],
         'couponEdit'=>[
         		'name'=>'coupon_edit'
         ],
         'couponDeleted'=>[
         		'name'=>'coupon_delete'
         ],
         'emailTemplateIndex'=>[
         		'name'=>'email_template_index'
         ],
         'emailTemplateCreate'=>[
         		'name'=>'email_template_create'
         ],
         'emailTemplateView'=>[
         		'name'=>'email_template_view'
         ],
         'emailTemplateEdit'=>[
         		'name'=>'email_template_edit'
         ],
         'emailTemplateDeleted'=>[
         		'name'=>'email_template_delete'
         ],
         'orderDetailIndex'=>[
         		'name'=>'order_detail_index'
         ],
         'orderDetailView'=>[
         		'name'=>'order_detail_view'
         ],
         'orderDetailEdit'=>[
         		'name'=>'order_detail_edit'
         ],
         'contactUsIndex'=>[
         		'name'=>'contact_us_index'
         ],
         'contactUsView'=>[
         		'name'=>'contact_us_view'
         ],
         'contactUsReply'=>[
         		'name'=>'contact_us_reply'
         ],
    ],    
];
?>